# Numpy - Arrays

In [13]:
import numpy as np

## Arrays

In [14]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

### Data Types

In [15]:
a = np.array([1, 2, 3, 4], dtype="f")
a

array([1., 2., 3., 4.], dtype=float32)

## Scalars

#### You can directly apply scalar arithmetic

In [16]:
a + 2
a

array([1., 2., 3., 4.], dtype=float32)

In [17]:
a - 3
a

array([1., 2., 3., 4.], dtype=float32)

In [18]:
a * 4
a

array([1., 2., 3., 4.], dtype=float32)

In [19]:
a / 5
a

array([1., 2., 3., 4.], dtype=float32)

In [20]:
a ** 2
a

array([1., 2., 3., 4.], dtype=float32)

## Vector Arithmetics

### Addition

In [21]:
b = np.array([4, 3, 2, 1])
a + b

array([5., 5., 5., 5.])

### Hadamard / Schur Product (element wise multiplication)


In [28]:
a = np.array([1, 2, 3])
b = np.array([4, 3, 2])
a * b

array([4, 6, 6])

### Dot product

In [29]:
a.dot(b)
# 1*4 + 2*3 + 3*2 + 4*1

np.int64(16)

#### shorthand

In [30]:
a@b

np.int64(16)

## Cross Product

In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 3, 2])
np.cross(a, b)

array([-5, 10, -5])