# Numpy

In [1]:
import numpy as np

## Arrays

In [26]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

### Data Types

In [27]:
a = np.array([1, 2, 3, 4], dtype="f")
a

array([1., 2., 3., 4.], dtype=float32)

### Basic Operations

#### You can directly apply scalar arithmetic

In [34]:
a + 2
a

array([5., 6., 7., 8.], dtype=float32)

In [35]:
a - 3
a

array([2., 3., 4., 5.], dtype=float32)

In [37]:
a * 4
a

array([32., 48., 64., 80.], dtype=float32)

In [38]:
a / 5
a

array([ 6.4,  9.6, 12.8, 16. ], dtype=float32)

In [42]:
a ** 2
a

array([ 1677.7218,  8493.466 , 26843.549 , 65536.    ], dtype=float32)

#### Arrays can be directly added as well

In [40]:
b = np.array([4, 3, 2, 1])
a + b

array([ 44.9600029 ,  95.16000366, 165.8400116 , 257.        ])

In [45]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a * b

array([4, 6, 6, 4])

#### Dot product

In [48]:
a.dot(b)
# 1*4 + 2*3 + 3*2 + 4*1

20