# Numpy

In [1]:
import numpy as np

## Arrays

In [2]:
a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

### Data Types

In [3]:
a = np.array([1, 2, 3, 4], dtype="f")
a

array([1., 2., 3., 4.], dtype=float32)

### Basic Operations

#### You can directly apply scalar arithmetic

In [4]:
a + 2
a

array([1., 2., 3., 4.], dtype=float32)

In [5]:
a - 3
a

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a * 4
a

array([1., 2., 3., 4.], dtype=float32)

In [7]:
a / 5
a

array([1., 2., 3., 4.], dtype=float32)

In [8]:
a ** 2
a

array([1., 2., 3., 4.], dtype=float32)

#### Arrays can be directly added as well

In [9]:
b = np.array([4, 3, 2, 1])
a + b

array([5., 5., 5., 5.])

In [10]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
a * b

array([4, 6, 6, 4])

#### Dot product

In [11]:
a.dot(b)
# 1*4 + 2*3 + 3*2 + 4*1

np.int64(20)