# Numpy - Arrays

In [1]:
import numpy as np

## Arrays

In [2]:
a = np.array([1, 2, 3)
a

array([1, 2, 3, 4])

In [14]:
b = a.tolist()
b

[1, 2, 3]

### Data Types

In [15]:
a.dtype

dtype('int64')

In [3]:
a = np.array([1, 2, 3, 4], dtype="f")
a

array([1., 2., 3., 4.], dtype=float32)

## Scalars

#### You can directly apply scalar arithmetic

In [4]:
a + 2
a

array([1., 2., 3., 4.], dtype=float32)

In [5]:
a - 3
a

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a * 4
a

array([1., 2., 3., 4.], dtype=float32)

In [7]:
a / 5
a

array([1., 2., 3., 4.], dtype=float32)

In [8]:
a ** 2
a

array([1., 2., 3., 4.], dtype=float32)

## Vector Arithmetics

### Addition

In [9]:
b = np.array([4, 3, 2, 1])
a + b

array([5., 5., 5., 5.])

### Hadamard / Schur Product (element wise multiplication)


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 3, 2])
a * b

array([4, 6, 6])

### Dot product

In [11]:
a.dot(b)
# 1*4 + 2*3 + 3*2 + 4*1

np.int64(16)

#### shorthand

In [12]:
a@b

np.int64(16)

## Cross Product

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 3, 2])
np.cross(a, b)

array([-5, 10, -5])