# Matrices

In [1]:
import numpy as np

In [8]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

## Matrix multiplication

In [2]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
a.dot(b)

array([[19, 22],
       [43, 50]])

In [3]:
np.matmul(a, b)

array([[19, 22],
       [43, 50]])

In [2]:

a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

## Reshaping Arrays

In [3]:
reshaped = a.reshape([2, 4])
reshaped



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
a.reshape([4, -1])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.reshape([-1])

array([1, 2, 3, 4, 5, 6])

In [7]:
b.shape

(2, 3)

## matmul

In [8]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.matmul(a, b)
c

array([[19, 22],
       [43, 50]])

#### shorthand

In [10]:
a@b


array([[19, 22],
       [43, 50]])

## einsum

In [6]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

### Sum all indices

In [ ]:
result = np.einsum('ij->',a)
result

In [5]:
a = np.array([[1, 2], [3, 4]])
np.einsum('ii', a)

np.int64(5)

### Transpose

In [ ]:
result = np.einsum('ij->ji', a)
result

### Matrix Multiplikation

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.einsum('ik,kj->ij', a, b)
result

### Outer Product (Dyadic Product)


In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,j->ij', a, b)
result

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])