# Matrices

In [8]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

Reshaping Arrays

In [3]:
reshaped = a.reshape([2, 4])
reshaped



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
a.reshape([4, -1])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [5]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
b.reshape([-1])

array([1, 2, 3, 4, 5, 6])

In [7]:
b.shape

(2, 3)