# Matrices

In [1]:
import numpy as np
a = np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

## Reshaping Arrays

In [2]:
reshaped = a.reshape([2, 4])
reshaped



array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [3]:
a.reshape([4, -1])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [4]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b.reshape([-1])

array([1, 2, 3, 4, 5, 6])

In [6]:
b.shape

(2, 3)

## matmul

In [10]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.matmul(a, b)
c

array([[19, 22],
       [43, 50]])

In [30]:
c = a@b
c

np.int64(32)

## einsum

In [19]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

### Sum all indices

In [20]:
result = np.einsum('ij->',a)
result

np.int64(10)

### Transpose

In [23]:
result = np.einsum('ij->ji', a)
result

array([[1, 3],
       [2, 4]])

### Matrix Multiplikation

In [25]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.einsum('ik,kj->ij', a, b)
result

array([[19, 22],
       [43, 50]])

### Outer Product (Dyadic Product)


In [26]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
result = np.einsum('i,j->ij', a, b)
result

array([[ 4,  5,  6],
       [ 8, 10, 12],
       [12, 15, 18]])

array([-3,  6, -3])